import express, { Request, Response } from 'express';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import { createServer as createViteServer } from 'vite';
import Database from 'better-sqlite3';

const DATA_DIR = path.join(process.cwd(), '.data');
const THUMBS_DIR = path.join(DATA_DIR, 'thumbnails');
for (const dir of [DATA_DIR, THUMBS_DIR]) {
  if (!fs.existsSync(dir)) {
    try { fs.mkdirSync(dir, { recursive: true }); } catch (_) {}
  }
}
const DB_FILE_PATH = path.join(DATA_DIR, 'fits_catalog.sqlite');

const SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS fits_images (
  id TEXT PRIMARY KEY,
  file_name TEXT NOT NULL,
  file_path TEXT,
  file_size INTEGER,
  file_hash TEXT,
  object_name TEXT,
  object_category TEXT,
  image_type TEXT,
  exposure_time REAL,
  sensor_temp REAL,
  rotation_angle REAL,
  date_obs TEXT,
  filter_name TEXT,
  telescope TEXT,
  camera TEXT,
  focal_length REAL,
  gain INTEGER,
  bayer_pattern TEXT,
  ra TEXT,
  dec TEXT,
  airmass REAL,
  width INTEGER,
  height INTEGER,
  bitpix INTEGER,
  thumbnail_url TEXT,
  headers_json TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  custom_tags TEXT,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_object ON fits_images(object_name);
CREATE INDEX IF NOT EXISTS idx_type ON fits_images(image_type);
CREATE INDEX IF NOT EXISTS idx_date ON fits_images(date_obs);
CREATE INDEX IF NOT EXISTS idx_filter ON fits_images(filter_name);
CREATE INDEX IF NOT EXISTS idx_temp ON fits_images(sensor_temp);
CREATE INDEX IF NOT EXISTS idx_exposure ON fits_images(exposure_time);
CREATE INDEX IF NOT EXISTS idx_hash ON fits_images(file_hash);
CREATE INDEX IF NOT EXISTS idx_path ON fits_images(file_path);
`;

/**
 * NOTE ON ARCHITECTURE (read this before touching the DB layer again):
 *
 * The previous version of this server used `sql.js`, which is SQLite compiled to
 * WASM and kept ENTIRELY IN NODE'S MEMORY. Every single write (even one row)
 * called db.export() to serialize the *whole* database back into a fresh
 * Buffer and rewrite the *entire* file to disk. On top of that, JPEG preview
 * thumbnails (base64, ~100-400 KB each) were stored as TEXT directly inside
 * the SQL rows.
 *
 * That combination is fine for a handful of images, but it does not scale:
 * for a real astrophotography archive (hundreds or thousands of FITS frames
 * per import), memory usage grew without bound and the process would
 * eventually be killed by the OS (confirmed by load-testing: RSS grew from
 * ~400MB to ~2.9GB and climbing after ~3000 simulated frames, with no sign of
 * plateauing). That is the "el programa peta quan puges els fitxers des del
 * directori" bug.
 *
 * The fix has two parts:
 *   1. Use `better-sqlite3`, a native binding to a real, file-backed SQLite
 *      database (with WAL mode). Writes are normal incremental SQL
 *      statements; nothing re-serializes the whole DB on every insert.
 *   2. Store thumbnails as individual JPEG/SVG files on disk
 *      (.data/thumbnails/<id>.<ext>) and keep only a short relative path in
 *      the `thumbnail_url` column, instead of embedding the base64 blob in
 *      every row. This keeps row size (and therefore query/index/export
 *      cost) tiny regardless of catalog size.
 */

const db = new Database(DB_FILE_PATH);
db.pragma('journal_mode = WAL');
db.pragma('synchronous = NORMAL');
db.exec(SCHEMA_SQL);

// --- Thumbnail file storage helpers -----------------------------------

function sanitizeId(id: string): string {
  return String(id).replace(/[^A-Za-z0-9_-]/g, '_').slice(0, 128);
}

/**
 * Accepts either:
 *  - a data: URL (base64 JPEG/PNG or utf8-encoded SVG) freshly generated by
 *    the browser's canvas — written to disk here, returns the new relative path.
 *  - anything else (an existing relative path like "/thumbnails/x.jpg", or
 *    an already-external URL) — returned untouched, since there's nothing to do.
 */
function persistThumbnailIfNeeded(id: string, thumbnailUrl: string): string {
  if (!thumbnailUrl || !thumbnailUrl.startsWith('data:')) {
    return thumbnailUrl || '';
  }

  const match = /^data:([^;,]+)(;charset=[^;,]+)?(;base64)?,(.*)$/s.exec(thumbnailUrl);
  if (!match) return '';

  const mime = match[1];
  const isBase64 = !!match[3];
  const payload = match[4];

  let ext = 'jpg';
  if (mime.includes('svg')) ext = 'svg';
  else if (mime.includes('png')) ext = 'png';
  else if (mime.includes('jpeg') || mime.includes('jpg')) ext = 'jpg';

  const safeId = sanitizeId(id);
  const fileName = `${safeId}.${ext}`;
  const filePath = path.join(THUMBS_DIR, fileName);

  try {
    const buffer = isBase64
      ? Buffer.from(payload, 'base64')
      : Buffer.from(decodeURIComponent(payload), 'utf8');
    fs.writeFileSync(filePath, buffer);
    return `/thumbnails/${fileName}`;
  } catch (err) {
    console.error(`Error writing thumbnail for ${id}:`, err);
    return '';
  }
}

function deleteThumbnailFile(thumbnailUrl: string | null | undefined) {
  if (!thumbnailUrl || !thumbnailUrl.startsWith('/thumbnails/')) return;
  const fileName = path.basename(thumbnailUrl);
  const filePath = path.join(THUMBS_DIR, fileName);
  try {
    if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
  } catch (_) {}
}

// --- Prepared statements -------------------------------------------------

const upsertStmt = db.prepare(`
  INSERT INTO fits_images (
    id, file_name, file_path, file_size, file_hash, object_name, object_category,
    image_type, exposure_time, sensor_temp, rotation_angle, date_obs, filter_name,
    telescope, camera, focal_length, gain, bayer_pattern, ra, dec, airmass, width, height, bitpix,
    thumbnail_url, headers_json, custom_tags, notes
  ) VALUES (
    @id, @file_name, @file_path, @file_size, @file_hash, @object_name, @object_category,
    @image_type, @exposure_time, @sensor_temp, @rotation_angle, @date_obs, @filter_name,
    @telescope, @camera, @focal_length, @gain, @bayer_pattern, @ra, @dec, @airmass, @width, @height, @bitpix,
    @thumbnail_url, @headers_json, @custom_tags, @notes
  )
  ON CONFLICT(id) DO UPDATE SET
    file_name=excluded.file_name,
    file_path=excluded.file_path,
    file_size=excluded.file_size,
    file_hash=excluded.file_hash,
    object_name=excluded.object_name,
    object_category=excluded.object_category,
    image_type=excluded.image_type,
    exposure_time=excluded.exposure_time,
    sensor_temp=excluded.sensor_temp,
    rotation_angle=excluded.rotation_angle,
    date_obs=excluded.date_obs,
    filter_name=excluded.filter_name,
    telescope=excluded.telescope,
    camera=excluded.camera,
    focal_length=excluded.focal_length,
    gain=excluded.gain,
    bayer_pattern=excluded.bayer_pattern,
    ra=excluded.ra,
    dec=excluded.dec,
    airmass=excluded.airmass,
    width=excluded.width,
    height=excluded.height,
    bitpix=excluded.bitpix,
    thumbnail_url=excluded.thumbnail_url,
    headers_json=excluded.headers_json,
    custom_tags=excluded.custom_tags,
    notes=excluded.notes
`);

const insertManyTx = db.transaction((rows: any[]) => {
  let count = 0;
  for (const row of rows) {
    upsertStmt.run(row);
    count++;
  }
  return count;
});

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: '25mb' }));
  app.use(express.urlencoded({ extended: true, limit: '25mb' }));

  // Serve generated thumbnail files directly (cheap static files, not DB blobs)
  app.use('/thumbnails', express.static(THUMBS_DIR, { maxAge: '30d', immutable: true }));

  app.get('/api/health', (req: Request, res: Response) => {
    res.json({ status: 'ok', time: new Date().toISOString() });
  });

  // Get all images with optional filters
  app.get('/api/images', (req: Request, res: Response) => {
    try {
      const {
        search,
        image_type,
        filter_name,
        min_exposure,
        max_exposure,
        min_temp,
        max_temp,
        limit = '50000',
        offset = '0'
      } = req.query;

      let query = 'SELECT * FROM fits_images WHERE 1=1';
      const params: any[] = [];

      if (search && typeof search === 'string' && search.trim()) {
        query += ' AND (object_name LIKE ? OR file_name LIKE ? OR telescope LIKE ? OR camera LIKE ? OR custom_tags LIKE ?)';
        const searchTerm = `%${search.trim()}%`;
        params.push(searchTerm, searchTerm, searchTerm, searchTerm, searchTerm);
      }

      if (image_type && typeof image_type === 'string' && image_type !== 'ALL') {
        query += ' AND UPPER(image_type) = UPPER(?)';
        params.push(image_type);
      }

      if (filter_name && typeof filter_name === 'string' && filter_name !== 'ALL') {
        query += ' AND UPPER(filter_name) = UPPER(?)';
        params.push(filter_name);
      }

      if (min_exposure && !isNaN(Number(min_exposure))) {
        query += ' AND exposure_time >= ?';
        params.push(Number(min_exposure));
      }

      if (max_exposure && !isNaN(Number(max_exposure))) {
        query += ' AND exposure_time <= ?';
        params.push(Number(max_exposure));
      }

      if (min_temp && !isNaN(Number(min_temp))) {
        query += ' AND sensor_temp >= ?';
        params.push(Number(min_temp));
      }

      if (max_temp && !isNaN(Number(max_temp))) {
        query += ' AND sensor_temp <= ?';
        params.push(Number(max_temp));
      }

      query += ' ORDER BY date_obs DESC, created_at DESC LIMIT ? OFFSET ?';
      params.push(parseInt(limit as string, 10) || 50000, parseInt(offset as string, 10) || 0);

      const rows = db.prepare(query).all(...params);
      const totalRow = db.prepare('SELECT COUNT(*) as total FROM fits_images').get() as any;

      res.json({ success: true, count: rows.length, total: totalRow?.total || 0, images: rows });
    } catch (err: any) {
      console.error('Error fetching images:', err);
      res.status(500).json({ success: false, error: err.message, images: [] });
    }
  });

  // Check which (file_path, file_size) or file_hash combos are already known,
  // so the client can skip re-parsing/re-uploading files it has already imported
  // (used when re-scanning a directory that already has some frames catalogued).
  app.post('/api/images/known', (req: Request, res: Response) => {
    try {
      const { hashes = [], paths = [] } = req.body || {};
      const knownHashes = new Set<string>();
      const knownPaths = new Set<string>();

      if (Array.isArray(hashes) && hashes.length > 0) {
        const placeholders = hashes.map(() => '?').join(',');
        const rows = db.prepare(
          `SELECT DISTINCT file_hash FROM fits_images WHERE file_hash IN (${placeholders}) AND file_hash IS NOT NULL AND file_hash != ''`
        ).all(...hashes) as any[];
        rows.forEach(r => knownHashes.add(r.file_hash));
      }

      if (Array.isArray(paths) && paths.length > 0) {
        const placeholders = paths.map(() => '?').join(',');
        const rows = db.prepare(
          `SELECT DISTINCT file_path FROM fits_images WHERE file_path IN (${placeholders})`
        ).all(...paths) as any[];
        rows.forEach(r => knownPaths.add(r.file_path));
      }

      res.json({ success: true, knownHashes: Array.from(knownHashes), knownPaths: Array.from(knownPaths) });
    } catch (err: any) {
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // Batch insert/upsert images into SQL database (single transaction, no full-DB export)
  app.post('/api/images/batch', (req: Request, res: Response) => {
    try {
      const { images } = req.body;

      if (!Array.isArray(images) || images.length === 0) {
        return res.json({ success: true, count: 0 });
      }

      const rows = images.map((img: any) => {
        const id = img.id || `${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
        const headersJson = typeof img.headers_json === 'object' ? JSON.stringify(img.headers_json) : (img.headers_json || '{}');
        const thumbnailUrl = persistThumbnailIfNeeded(id, img.thumbnail_url || '');

        return {
          id,
          file_name: img.file_name || 'unknown.fits',
          file_path: img.file_path || '',
          file_size: img.file_size || 0,
          file_hash: img.file_hash || '',
          object_name: img.object_name || 'Desconegut',
          object_category: img.object_category || 'Deep Sky',
          image_type: img.image_type || 'LIGHT',
          exposure_time: img.exposure_time !== undefined ? Number(img.exposure_time) : 0,
          sensor_temp: img.sensor_temp !== null && img.sensor_temp !== undefined ? Number(img.sensor_temp) : null,
          rotation_angle: img.rotation_angle !== null && img.rotation_angle !== undefined ? Number(img.rotation_angle) : null,
          date_obs: img.date_obs || new Date().toISOString(),
          filter_name: img.filter_name || 'None',
          telescope: img.telescope || '',
          camera: img.camera || '',
          focal_length: img.focal_length !== null && img.focal_length !== undefined ? Number(img.focal_length) : null,
          gain: img.gain !== null && img.gain !== undefined ? Number(img.gain) : null,
          bayer_pattern: img.bayer_pattern || '',
          ra: img.ra || '',
          dec: img.dec || '',
          airmass: img.airmass !== null && img.airmass !== undefined ? Number(img.airmass) : null,
          width: img.width || 0,
          height: img.height || 0,
          bitpix: img.bitpix || 16,
          thumbnail_url: thumbnailUrl,
          headers_json: headersJson,
          custom_tags: img.custom_tags || '',
          notes: img.notes || ''
        };
      });

      const inserted = insertManyTx(rows);
      res.json({ success: true, count: inserted });
    } catch (err: any) {
      console.error('Error saving batch images:', err);
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // Delete image by ID
  app.delete('/api/images/:id', (req: Request, res: Response) => {
    try {
      const { id } = req.params;
      const existing = db.prepare('SELECT thumbnail_url FROM fits_images WHERE id = ?').get(id) as any;
      db.prepare('DELETE FROM fits_images WHERE id = ?').run(id);
      if (existing) deleteThumbnailFile(existing.thumbnail_url);
      res.json({ success: true });
    } catch (err: any) {
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // Clear all images
  app.post('/api/images/clear', (req: Request, res: Response) => {
    try {
      db.prepare('DELETE FROM fits_images').run();
      // Wipe all thumbnail files too, rather than leaking them on disk forever
      try {
        for (const f of fs.readdirSync(THUMBS_DIR)) {
          fs.unlinkSync(path.join(THUMBS_DIR, f));
        }
      } catch (_) {}
      res.json({ success: true });
    } catch (err: any) {
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // Execute arbitrary SQL query (for SQL Explorer console)
  app.post('/api/sql/execute', (req: Request, res: Response) => {
    try {
      const { sql } = req.body;

      if (!sql || typeof sql !== 'string') {
        return res.status(400).json({ success: false, error: 'Missing SQL query' });
      }

      const trimmed = sql.trim();
      const isSelect = trimmed.toUpperCase().startsWith('SELECT') || trimmed.toUpperCase().startsWith('PRAGMA') || trimmed.toUpperCase().startsWith('EXPLAIN');

      if (isSelect) {
        const rows = db.prepare(trimmed).all() as Record<string, any>[];
        const columns = rows.length > 0 ? Object.keys(rows[0]) : [];
        return res.json({ success: true, columns, rows, rowCount: rows.length });
      } else {
        db.exec(trimmed);
        return res.json({ success: true, message: 'Query executed successfully' });
      }
    } catch (err: any) {
      console.error('SQL Execution Error:', err);
      res.status(400).json({ success: false, error: err.message });
    }
  });

  // Export full SQL database dump or SQLite binary
  app.get('/api/database/export', (req: Request, res: Response) => {
    try {
      const format = req.query.format || 'sqlite';

      if (format === 'sqlite') {
        // Flush WAL into the main file before sending a consistent snapshot
        db.pragma('wal_checkpoint(TRUNCATE)');
        const data = fs.readFileSync(DB_FILE_PATH);
        res.setHeader('Content-Type', 'application/x-sqlite3');
        res.setHeader('Content-Disposition', 'attachment; filename="fits_catalog.sqlite"');
        return res.send(data);
      } else if (format === 'sql') {
        const rows = db.prepare('SELECT * FROM fits_images').all() as Record<string, any>[];
        let dump = `-- FITS Astro Catalog SQL Dump\n-- Generated on ${new Date().toISOString()}\n\n`;
        dump += `CREATE TABLE IF NOT EXISTS fits_images (\n  id TEXT PRIMARY KEY,\n  file_name TEXT NOT NULL,\n  file_path TEXT,\n  file_size INTEGER,\n  file_hash TEXT,\n  object_name TEXT,\n  object_category TEXT,\n  image_type TEXT,\n  exposure_time REAL,\n  sensor_temp REAL,\n  rotation_angle REAL,\n  date_obs TEXT,\n  filter_name TEXT,\n  telescope TEXT,\n  camera TEXT,\n  focal_length REAL,\n  gain INTEGER,\n  bayer_pattern TEXT,\n  ra TEXT,\n  dec TEXT,\n  airmass REAL,\n  width INTEGER,\n  height INTEGER,\n  bitpix INTEGER,\n  thumbnail_url TEXT,\n  headers_json TEXT,\n  created_at TEXT DEFAULT CURRENT_TIMESTAMP,\n  custom_tags TEXT,\n  notes TEXT\n);\n\n`;

        if (rows.length > 0) {
          const cols = Object.keys(rows[0]);
          for (const row of rows) {
            const valStrings = cols.map(c => {
              const v = row[c];
              if (v === null || v === undefined) return 'NULL';
              if (typeof v === 'number') return v;
              return `'${String(v).replace(/'/g, "''")}'`;
            });
            dump += `INSERT OR REPLACE INTO fits_images (${cols.join(', ')}) VALUES (${valStrings.join(', ')});\n`;
          }
        }
        res.setHeader('Content-Type', 'text/plain; charset=utf-8');
        res.setHeader('Content-Disposition', 'attachment; filename="fits_catalog_dump.sql"');
        return res.send(dump);
      } else {
        res.status(400).json({ error: 'Unsupported export format' });
      }
    } catch (err: any) {
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // Get aggregated stats for astronomy sessions
  app.get('/api/stats', (req: Request, res: Response) => {
    try {
      const overview = db.prepare(`
        SELECT 
          COUNT(*) as total_images,
          COALESCE(SUM(exposure_time), 0) as total_exposure_sec,
          COUNT(DISTINCT object_name) as distinct_objects,
          COUNT(DISTINCT filter_name) as distinct_filters,
          AVG(sensor_temp) as avg_temp
        FROM fits_images
      `).get();

      const typeBreakdown = db.prepare(`
        SELECT image_type, COUNT(*) as count, SUM(exposure_time) as total_exp
        FROM fits_images
        GROUP BY image_type
      `).all();

      const objectBreakdown = db.prepare(`
        SELECT object_name, COUNT(*) as count, SUM(exposure_time) as total_exp
        FROM fits_images
        WHERE object_name IS NOT NULL AND object_name != ''
        GROUP BY object_name
        ORDER BY count DESC
        LIMIT 10
      `).all();

      const filterBreakdown = db.prepare(`
        SELECT filter_name, COUNT(*) as count, SUM(exposure_time) as total_exp
        FROM fits_images
        WHERE filter_name IS NOT NULL AND filter_name != ''
        GROUP BY filter_name
        ORDER BY count DESC
      `).all();

      res.json({ success: true, overview, typeBreakdown, objectBreakdown, filterBreakdown });
    } catch (err: any) {
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // Vite middleware for development or static serving for production
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req: Request, res: Response) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`FITS Astro Classifier server running at http://0.0.0.0:${PORT}`);
  });
}

process.on('unhandledRejection', (reason) => {
  console.error('Unhandled rejection:', reason);
});

startServer();
